// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts": {
    params: {};
  };
  "/posts/:postId/comments": {
    params: {
      "postId": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/posts" | "/posts/:postId/comments" | "/users" | "/users/:userId" | "/*";
  };
  "./layouts/main-layout/main-layout.tsx": {
    id: "layouts/main-layout/main-layout";
    page: "/" | "/posts" | "/posts/:postId/comments" | "/users" | "/users/:userId";
  };
  "./pages/main-page/main-page.tsx": {
    id: "pages/main-page/main-page";
    page: "/";
  };
  "./pages/posts-list-page/posts-list-page.tsx": {
    id: "pages/posts-list-page/posts-list-page";
    page: "/posts";
  };
  "./pages/post-comments-page/post-comments-page.tsx": {
    id: "pages/post-comments-page/post-comments-page";
    page: "/posts/:postId/comments";
  };
  "./pages/users-list-page/users-list-page.tsx": {
    id: "pages/users-list-page/users-list-page";
    page: "/users";
  };
  "./pages/user-info-page/user-info-page.tsx": {
    id: "pages/user-info-page/user-info-page";
    page: "/users/:userId";
  };
  "./pages/not-found/not-found.tsx": {
    id: "pages/not-found/not-found";
    page: "/*";
  };
};