// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "./layouts/main-layout/main-layout.tsx": {
    id: "layouts/main-layout/main-layout";
    page: "/";
  };
  "./pages/main-pages/main-page.tsx": {
    id: "pages/main-pages/main-page";
    page: "/";
  };
  "./pages/not-found/not-found.tsx": {
    id: "pages/not-found/not-found";
    page: "/*";
  };
};